In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

driver = webdriver.Chrome()

driver.get("https://www.flipkart.com/")
wait = WebDriverWait(driver, 10)  # Wait up to 10 seconds

driver.maximize_window()  # maximize window

# Login page

driver.find_element(By.XPATH,"//div[@class='H6-NpN _3N4_BX']").click()  # click login button
time.sleep(2)

driver.find_element(By.XPATH,"//input[@class='r4vIwl BV+Dqf']").send_keys("7588716151" + Keys.ENTER)  
time.sleep(10)
driver.find_element(By.XPATH,"//button[@class='QqFHMw llMuju M5XAsp' and contains(text(),'Verify')]").click()

# Creating Empty List
books_detail = []

# search book
search_box = wait.until(EC.presence_of_element_located((By.XPATH, "//input[@class='Pke_EE']")))
search_box.send_keys("data science books" + Keys.ENTER)

# Number of Pages
for page in range(1, 3):
    print(f"\n Scraping Page: {page}")

    # All book link
    book_links = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//a[@class='VJA3rP']")))
    
    # extract href from book_links
    links = [link.get_attribute("href") for link in book_links]


    for link in links:
        driver.get(link)
        try:
            # Wait for the title of the book to appear before continuing
            wait.until(EC.presence_of_element_located((By.XPATH, "//span[@class='VU-ZEz']")))
        except:
            print(f"Title not found for {link}, skipping...")


        # Get Title
        try:
            title = wait.until(EC.presence_of_element_located((By.XPATH,"//span[@class='VU-ZEz']"))).text
        except:
            title = "N/A"


        # Get Author
        try:
            author = wait.until(EC.presence_of_element_located((By.XPATH,"//a[@class='yN+eNk w9jEaj azBkHf']"))).text
        except:
            author = "N/A"


        # Get Selling price
        try:
            selling_price = wait.until(EC.presence_of_element_located((By.XPATH,"//div[@class='Nx9bqj CxhGGd']"))).text
        except:
            selling_price = "N/A"


        # Get MRP
        try:
            MRP = wait.until(EC.presence_of_element_located((By.XPATH,"//div[@class='yRaY8j A6+E6v']"))).text
        except:
            MRP = "N/A"

    
        # Get Discount
        try:
            discount = wait.until(EC.presence_of_element_located((By.XPATH,"//div[@class='UkUFwK WW8yVX']"))).text
        except:
            discount = "N/A"


        # Get Rating
        try:
            rating = wait.until(EC.presence_of_element_located((By.XPATH,"//div[@class='XQDdHH'][position()=1]"))).text
        except:
            rating = "N/A"
        
    
        # Get language
        try:
            language = wait.until(EC.presence_of_element_located((By.XPATH,"//li[@class='_7eSDEz' and contains(text(), 'Language')]"))).text
        except:
            language = "N/A"


        # Get Publisher
        try:
            publisher = wait.until(EC.presence_of_element_located((By.XPATH,"//li[@class='_7eSDEz'  and contains(text(),'Publisher')]"))).text
        except:
            publisher = "N/A"


        # Get Edition
        try:
            edition = wait.until(EC.presence_of_element_located((By.XPATH,"//li[@class='_7eSDEz'  and contains(text(),'Edition')]"))).text
        except:
            edition = "N/A"


        # Get Pages
        try:
            pages = wait.until(EC.presence_of_element_located((By.XPATH,"//li[@class='_7eSDEz' and contains(text(), 'Pages')]"))).text
        except:
            pages = "N/A"


        books_detail.append({
            "title":title,
            "author": author,
            "selling_price": selling_price,
            "MRP" : MRP,
            "discount" : discount,
            "rating": rating,
            "language": language,
            "publisher": publisher,
            "edition" : edition,
            "pages" : pages
        })


    # search again and go to next page
   
    try:
        driver.switch_to.default_content()
        next_button = wait.until(EC.element_to_be_clickable((By.XPATH,"//*[contains(@class, '_9QVEpD') or text()=Next]")))
        next_button.click()
        time.sleep(5)
    except:
        print("Next button not found. Maybe it's the last page.")
        break
           

# check list
books_detail

# close driver
driver.quit()

# import pandas library and convert list into dataframe
import pandas as pd

df = pd.DataFrame(books_detail)

df

The chromedriver version (134.0.6998.88) detected in PATH at C:\WINDOWS\chromedriver.exe might not be compatible with the detected chrome version (135.0.7049.115); currently, chromedriver 135.0.7049.114 is recommended for chrome 135.*, so it is advised to delete the driver in PATH and retry

 Scraping Page: 1

 Scraping Page: 2

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []